version: "3"
services:
  chrome_hub:
    image: selenium/node-chrome:4.2.0-20220527
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3

  selenium-hub:
    image: selenium/hub:4.2.0-20220527
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  selenium_debug_container:
    image: selenium/standalone-chrome-debug
    shm_size: 2gb
    ports:
      - 4555:4444
      - 5901:5900
